code --force --install-extension astro-build.astro-vscode
code --force --install-extension bmewburn.vscode-intelephense-client
code --force --install-extension bradlc.vscode-tailwindcss
code --force --install-extension bungcip.better-toml
code --force --install-extension cweijan.vscode-database-client2
code --force --install-extension dbaeumer.vscode-eslint
code --force --install-extension dotenv.dotenv-vscode
code --force --install-extension dqisme.sync-scroll
code --force --install-extension eamodio.gitlens
code --force --install-extension EditorConfig.EditorConfig
code --force --install-extension emmanuelbeziat.vscode-great-icons
code --force --install-extension Equinusocio.vsc-community-material-theme
code --force --install-extension equinusocio.vsc-material-theme-icons
code --force --install-extension golang.go
code --force --install-extension Gruntfuggly.todo-tree
code --force --install-extension Hridoy.adonisjs-snippets
code --force --install-extension luongnd.edge
code --force --install-extension lyzerk.linecounter
code --force --install-extension mkloubert.vscode-http-client
code --force --install-extension ms-azuretools.vscode-docker
code --force --install-extension ms-python.isort
code --force --install-extension ms-python.python
code --force --install-extension ms-python.vscode-pylance
code --force --install-extension ms-toolsai.jupyter
code --force --install-extension ms-toolsai.jupyter-keymap
code --force --install-extension ms-toolsai.jupyter-renderers
code --force --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --force --install-extension ms-toolsai.vscode-jupyter-slideshow
code --force --install-extension oderwat.indent-rainbow
code --force --install-extension onecentlin.laravel-blade
code --force --install-extension orsenkucher.vscode-graphql
code --force --install-extension PKief.material-icon-theme
code --force --install-extension Prisma.prisma
code --force --install-extension Prisma.prisma-insider
code --force --install-extension rvest.vs-code-prettier-eslint
code --force --install-extension SanderRonde.phpstan-vscode
code --force --install-extension sanity-io.vscode-sanity
code --force --install-extension shufo.vscode-blade-formatter
code --force --install-extension stef-k.adonis-js-goto-controller
code --force --install-extension stef-k.adonis-js-goto-view
code --force --install-extension svelte.svelte-vscode
code --force --install-extension tobiaswaelde.clockify-tracker
code --force --install-extension Vue.volar
code --force --install-extension Vue.vscode-typescript-vue-plugin
code --force --install-extension wix.vscode-import-cost
code --force --install-extension xdebug.php-debug
code --force --install-extension xdebug.php-pack
code --force --install-extension zobo.php-intellisense